package com.chimericdream.minekea.compat.byg;

import com.chimericdream.minekea.block.furniture.displaycases.GenericDisplayCase;
import com.chimericdream.minekea.block.furniture.displaycases.GenericDisplayCase.DisplayCaseSettings;

public class BygDisplayCases {
    public static final GenericDisplayCase ASPEN_DISPLAY_CASE;
    public static final GenericDisplayCase BAOBAB_DISPLAY_CASE;
    public static final GenericDisplayCase BLUE_ENCHANTED_DISPLAY_CASE;
    public static final GenericDisplayCase BULBIS_DISPLAY_CASE;
    public static final GenericDisplayCase CHERRY_DISPLAY_CASE;
    public static final GenericDisplayCase CIKA_DISPLAY_CASE;
    public static final GenericDisplayCase CYPRESS_DISPLAY_CASE;
    public static final GenericDisplayCase EBONY_DISPLAY_CASE;
    public static final GenericDisplayCase EMBUR_DISPLAY_CASE;
    public static final GenericDisplayCase ETHER_DISPLAY_CASE;
    public static final GenericDisplayCase FIR_DISPLAY_CASE;
    public static final GenericDisplayCase GREEN_ENCHANTED_DISPLAY_CASE;
    public static final GenericDisplayCase HOLLY_DISPLAY_CASE;
    public static final GenericDisplayCase IMPARIUS_DISPLAY_CASE;
    public static final GenericDisplayCase JACARANDA_DISPLAY_CASE;
    public static final GenericDisplayCase LAMENT_DISPLAY_CASE;
    public static final GenericDisplayCase MAHOGANY_DISPLAY_CASE;
    public static final GenericDisplayCase MAPLE_DISPLAY_CASE;
    public static final GenericDisplayCase NIGHTSHADE_DISPLAY_CASE;
    public static final GenericDisplayCase PALM_DISPLAY_CASE;
    public static final GenericDisplayCase PINE_DISPLAY_CASE;
    public static final GenericDisplayCase RAINBOW_EUCALYPTUS_DISPLAY_CASE;
    public static final GenericDisplayCase REDWOOD_DISPLAY_CASE;
    public static final GenericDisplayCase SKYRIS_DISPLAY_CASE;
    public static final GenericDisplayCase SYTHIAN_DISPLAY_CASE;
    public static final GenericDisplayCase WILLOW_DISPLAY_CASE;
    public static final GenericDisplayCase WITCH_HAZEL_DISPLAY_CASE;
    public static final GenericDisplayCase ZELKOVA_DISPLAY_CASE;

    public static final GenericDisplayCase STRIPPED_ASPEN_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_BAOBAB_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_BLUE_ENCHANTED_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_BULBIS_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_CHERRY_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_CIKA_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_CYPRESS_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_EBONY_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_EMBUR_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_ETHER_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_FIR_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_GREEN_ENCHANTED_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_HOLLY_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_IMPARIUS_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_JACARANDA_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_LAMENT_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_MAHOGANY_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_MAPLE_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_NIGHTSHADE_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_PALM_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_PINE_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_RAINBOW_EUCALYPTUS_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_REDWOOD_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_SKYRIS_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_SYTHIAN_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_WILLOW_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_WITCH_HAZEL_DISPLAY_CASE;
    public static final GenericDisplayCase STRIPPED_ZELKOVA_DISPLAY_CASE;

    static {
        ASPEN_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.ASPEN));
        BAOBAB_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.BAOBAB));
        BLUE_ENCHANTED_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.BLUE_ENCHANTED));
        BULBIS_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.BULBIS));
        CHERRY_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.CHERRY));
        CIKA_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.CIKA));
        CYPRESS_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.CYPRESS));
        EBONY_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.EBONY));
        EMBUR_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.EMBUR));
        ETHER_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.ETHER));
        FIR_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.FIR));
        GREEN_ENCHANTED_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.GREEN_ENCHANTED));
        HOLLY_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.HOLLY));
        IMPARIUS_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.IMPARIUS));
        JACARANDA_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.JACARANDA));
        LAMENT_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.LAMENT));
        MAHOGANY_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.MAHOGANY));
        MAPLE_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.MAPLE));
        NIGHTSHADE_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.NIGHTSHADE));
        PALM_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.PALM));
        PINE_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.PINE));
        RAINBOW_EUCALYPTUS_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.RAINBOW_EUCALYPTUS));
        REDWOOD_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.REDWOOD));
        SKYRIS_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.SKYRIS));
        SYTHIAN_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.SYTHIAN));
        WILLOW_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.WILLOW));
        WITCH_HAZEL_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.WITCH_HAZEL));
        ZELKOVA_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.ZELKOVA));

        STRIPPED_ASPEN_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.ASPEN).stripped());
        STRIPPED_BAOBAB_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.BAOBAB).stripped());
        STRIPPED_BLUE_ENCHANTED_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.BLUE_ENCHANTED).stripped());
        STRIPPED_BULBIS_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.BULBIS).stripped());
        STRIPPED_CHERRY_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.CHERRY).stripped());
        STRIPPED_CIKA_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.CIKA).stripped());
        STRIPPED_CYPRESS_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.CYPRESS).stripped());
        STRIPPED_EBONY_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.EBONY).stripped());
        STRIPPED_EMBUR_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.EMBUR).stripped());
        STRIPPED_ETHER_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.ETHER).stripped());
        STRIPPED_FIR_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.FIR).stripped());
        STRIPPED_GREEN_ENCHANTED_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.GREEN_ENCHANTED).stripped());
        STRIPPED_HOLLY_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.HOLLY).stripped());
        STRIPPED_IMPARIUS_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.IMPARIUS).stripped());
        STRIPPED_JACARANDA_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.JACARANDA).stripped());
        STRIPPED_LAMENT_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.LAMENT).stripped());
        STRIPPED_MAHOGANY_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.MAHOGANY).stripped());
        STRIPPED_MAPLE_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.MAPLE).stripped());
        STRIPPED_NIGHTSHADE_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.NIGHTSHADE).stripped());
        STRIPPED_PALM_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.PALM).stripped());
        STRIPPED_PINE_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.PINE).stripped());
        STRIPPED_RAINBOW_EUCALYPTUS_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.RAINBOW_EUCALYPTUS).stripped());
        STRIPPED_REDWOOD_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.REDWOOD).stripped());
        STRIPPED_SKYRIS_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.SKYRIS).stripped());
        STRIPPED_SYTHIAN_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.SYTHIAN).stripped());
        STRIPPED_WILLOW_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.WILLOW).stripped());
        STRIPPED_WITCH_HAZEL_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.WITCH_HAZEL).stripped());
        STRIPPED_ZELKOVA_DISPLAY_CASE = new GenericDisplayCase(new DisplayCaseSettings(BygBlockSettings.ZELKOVA).stripped());
    }

    public void register() {
        ASPEN_DISPLAY_CASE.register();
        BAOBAB_DISPLAY_CASE.register();
        BLUE_ENCHANTED_DISPLAY_CASE.register();
        BULBIS_DISPLAY_CASE.register();
        CHERRY_DISPLAY_CASE.register();
        CIKA_DISPLAY_CASE.register();
        CYPRESS_DISPLAY_CASE.register();
        EBONY_DISPLAY_CASE.register();
        EMBUR_DISPLAY_CASE.register();
        ETHER_DISPLAY_CASE.register();
        FIR_DISPLAY_CASE.register();
        GREEN_ENCHANTED_DISPLAY_CASE.register();
        HOLLY_DISPLAY_CASE.register();
        IMPARIUS_DISPLAY_CASE.register();
        JACARANDA_DISPLAY_CASE.register();
        LAMENT_DISPLAY_CASE.register();
        MAHOGANY_DISPLAY_CASE.register();
        MAPLE_DISPLAY_CASE.register();
        NIGHTSHADE_DISPLAY_CASE.register();
        PALM_DISPLAY_CASE.register();
        PINE_DISPLAY_CASE.register();
        RAINBOW_EUCALYPTUS_DISPLAY_CASE.register();
        REDWOOD_DISPLAY_CASE.register();
        SKYRIS_DISPLAY_CASE.register();
        SYTHIAN_DISPLAY_CASE.register();
        WILLOW_DISPLAY_CASE.register();
        WITCH_HAZEL_DISPLAY_CASE.register();
        ZELKOVA_DISPLAY_CASE.register();

        STRIPPED_ASPEN_DISPLAY_CASE.register();
        STRIPPED_BAOBAB_DISPLAY_CASE.register();
        STRIPPED_BLUE_ENCHANTED_DISPLAY_CASE.register();
        STRIPPED_BULBIS_DISPLAY_CASE.register();
        STRIPPED_CHERRY_DISPLAY_CASE.register();
        STRIPPED_CIKA_DISPLAY_CASE.register();
        STRIPPED_CYPRESS_DISPLAY_CASE.register();
        STRIPPED_EBONY_DISPLAY_CASE.register();
        STRIPPED_EMBUR_DISPLAY_CASE.register();
        STRIPPED_ETHER_DISPLAY_CASE.register();
        STRIPPED_FIR_DISPLAY_CASE.register();
        STRIPPED_GREEN_ENCHANTED_DISPLAY_CASE.register();
        STRIPPED_HOLLY_DISPLAY_CASE.register();
        STRIPPED_IMPARIUS_DISPLAY_CASE.register();
        STRIPPED_JACARANDA_DISPLAY_CASE.register();
        STRIPPED_LAMENT_DISPLAY_CASE.register();
        STRIPPED_MAHOGANY_DISPLAY_CASE.register();
        STRIPPED_MAPLE_DISPLAY_CASE.register();
        STRIPPED_NIGHTSHADE_DISPLAY_CASE.register();
        STRIPPED_PALM_DISPLAY_CASE.register();
        STRIPPED_PINE_DISPLAY_CASE.register();
        STRIPPED_RAINBOW_EUCALYPTUS_DISPLAY_CASE.register();
        STRIPPED_REDWOOD_DISPLAY_CASE.register();
        STRIPPED_SKYRIS_DISPLAY_CASE.register();
        STRIPPED_SYTHIAN_DISPLAY_CASE.register();
        STRIPPED_WILLOW_DISPLAY_CASE.register();
        STRIPPED_WITCH_HAZEL_DISPLAY_CASE.register();
        STRIPPED_ZELKOVA_DISPLAY_CASE.register();
    }
}
