package com.chimericdream.minekea.compat.byg;

import com.chimericdream.minekea.block.furniture.seating.GenericChair;
import com.chimericdream.minekea.block.furniture.seating.GenericChair.ChairSettings;
import com.chimericdream.minekea.block.furniture.seating.GenericStool;
import com.chimericdream.minekea.block.furniture.seating.GenericStool.StoolSettings;

public class BygSeats {
    public static final GenericChair ASPEN_CHAIR;
    public static final GenericChair BAOBAB_CHAIR;
    public static final GenericChair BLUE_ENCHANTED_CHAIR;
    public static final GenericChair BULBIS_CHAIR;
    public static final GenericChair CHERRY_CHAIR;
    public static final GenericChair CIKA_CHAIR;
    public static final GenericChair CYPRESS_CHAIR;
    public static final GenericChair EBONY_CHAIR;
    public static final GenericChair EMBUR_CHAIR;
    public static final GenericChair ETHER_CHAIR;
    public static final GenericChair FIR_CHAIR;
    public static final GenericChair GREEN_ENCHANTED_CHAIR;
    public static final GenericChair HOLLY_CHAIR;
    public static final GenericChair IMPARIUS_CHAIR;
    public static final GenericChair JACARANDA_CHAIR;
    public static final GenericChair LAMENT_CHAIR;
    public static final GenericChair MAHOGANY_CHAIR;
    public static final GenericChair MAPLE_CHAIR;
    public static final GenericChair NIGHTSHADE_CHAIR;
    public static final GenericChair PALM_CHAIR;
    public static final GenericChair PINE_CHAIR;
    public static final GenericChair RAINBOW_EUCALYPTUS_CHAIR;
    public static final GenericChair REDWOOD_CHAIR;
    public static final GenericChair SKYRIS_CHAIR;
    public static final GenericChair SYTHIAN_CHAIR;
    public static final GenericChair WILLOW_CHAIR;
    public static final GenericChair WITCH_HAZEL_CHAIR;
    public static final GenericChair ZELKOVA_CHAIR;

    public static final GenericStool ASPEN_STOOL;
    public static final GenericStool BAOBAB_STOOL;
    public static final GenericStool BLUE_ENCHANTED_STOOL;
    public static final GenericStool BULBIS_STOOL;
    public static final GenericStool CHERRY_STOOL;
    public static final GenericStool CIKA_STOOL;
    public static final GenericStool CYPRESS_STOOL;
    public static final GenericStool EBONY_STOOL;
    public static final GenericStool EMBUR_STOOL;
    public static final GenericStool ETHER_STOOL;
    public static final GenericStool FIR_STOOL;
    public static final GenericStool GREEN_ENCHANTED_STOOL;
    public static final GenericStool HOLLY_STOOL;
    public static final GenericStool IMPARIUS_STOOL;
    public static final GenericStool JACARANDA_STOOL;
    public static final GenericStool LAMENT_STOOL;
    public static final GenericStool MAHOGANY_STOOL;
    public static final GenericStool MAPLE_STOOL;
    public static final GenericStool NIGHTSHADE_STOOL;
    public static final GenericStool PALM_STOOL;
    public static final GenericStool PINE_STOOL;
    public static final GenericStool RAINBOW_EUCALYPTUS_STOOL;
    public static final GenericStool REDWOOD_STOOL;
    public static final GenericStool SKYRIS_STOOL;
    public static final GenericStool SYTHIAN_STOOL;
    public static final GenericStool WILLOW_STOOL;
    public static final GenericStool WITCH_HAZEL_STOOL;
    public static final GenericStool ZELKOVA_STOOL;

    static {
        ASPEN_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.ASPEN));
        BAOBAB_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.BAOBAB));
        BLUE_ENCHANTED_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.BLUE_ENCHANTED));
        BULBIS_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.BULBIS));
        CHERRY_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.CHERRY));
        CIKA_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.CIKA));
        CYPRESS_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.CYPRESS));
        EBONY_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.EBONY));
        EMBUR_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.EMBUR));
        ETHER_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.ETHER));
        FIR_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.FIR));
        GREEN_ENCHANTED_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.GREEN_ENCHANTED));
        HOLLY_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.HOLLY));
        IMPARIUS_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.IMPARIUS));
        JACARANDA_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.JACARANDA));
        LAMENT_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.LAMENT));
        MAHOGANY_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.MAHOGANY));
        MAPLE_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.MAPLE));
        NIGHTSHADE_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.NIGHTSHADE));
        PALM_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.PALM));
        PINE_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.PINE));
        RAINBOW_EUCALYPTUS_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.RAINBOW_EUCALYPTUS));
        REDWOOD_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.REDWOOD));
        SKYRIS_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.SKYRIS));
        SYTHIAN_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.SYTHIAN));
        WILLOW_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.WILLOW));
        WITCH_HAZEL_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.WITCH_HAZEL));
        ZELKOVA_CHAIR = new GenericChair(new ChairSettings(BygBlockSettings.ZELKOVA));

        ASPEN_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.ASPEN));
        BAOBAB_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.BAOBAB));
        BLUE_ENCHANTED_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.BLUE_ENCHANTED));
        BULBIS_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.BULBIS));
        CHERRY_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.CHERRY));
        CIKA_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.CIKA));
        CYPRESS_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.CYPRESS));
        EBONY_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.EBONY));
        EMBUR_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.EMBUR));
        ETHER_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.ETHER));
        FIR_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.FIR));
        GREEN_ENCHANTED_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.GREEN_ENCHANTED));
        HOLLY_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.HOLLY));
        IMPARIUS_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.IMPARIUS));
        JACARANDA_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.JACARANDA));
        LAMENT_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.LAMENT));
        MAHOGANY_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.MAHOGANY));
        MAPLE_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.MAPLE));
        NIGHTSHADE_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.NIGHTSHADE));
        PALM_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.PALM));
        PINE_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.PINE));
        RAINBOW_EUCALYPTUS_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.RAINBOW_EUCALYPTUS));
        REDWOOD_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.REDWOOD));
        SKYRIS_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.SKYRIS));
        SYTHIAN_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.SYTHIAN));
        WILLOW_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.WILLOW));
        WITCH_HAZEL_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.WITCH_HAZEL));
        ZELKOVA_STOOL = new GenericStool(new StoolSettings(BygBlockSettings.ZELKOVA));
    }

    public void register() {
        ASPEN_CHAIR.register();
        BAOBAB_CHAIR.register();
        BLUE_ENCHANTED_CHAIR.register();
        BULBIS_CHAIR.register();
        CHERRY_CHAIR.register();
        CIKA_CHAIR.register();
        CYPRESS_CHAIR.register();
        EBONY_CHAIR.register();
        EMBUR_CHAIR.register();
        ETHER_CHAIR.register();
        FIR_CHAIR.register();
        GREEN_ENCHANTED_CHAIR.register();
        HOLLY_CHAIR.register();
        IMPARIUS_CHAIR.register();
        JACARANDA_CHAIR.register();
        LAMENT_CHAIR.register();
        MAHOGANY_CHAIR.register();
        MAPLE_CHAIR.register();
        NIGHTSHADE_CHAIR.register();
        PALM_CHAIR.register();
        PINE_CHAIR.register();
        RAINBOW_EUCALYPTUS_CHAIR.register();
        REDWOOD_CHAIR.register();
        SKYRIS_CHAIR.register();
        SYTHIAN_CHAIR.register();
        WILLOW_CHAIR.register();
        WITCH_HAZEL_CHAIR.register();
        ZELKOVA_CHAIR.register();

        ASPEN_STOOL.register();
        BAOBAB_STOOL.register();
        BLUE_ENCHANTED_STOOL.register();
        BULBIS_STOOL.register();
        CHERRY_STOOL.register();
        CIKA_STOOL.register();
        CYPRESS_STOOL.register();
        EBONY_STOOL.register();
        EMBUR_STOOL.register();
        ETHER_STOOL.register();
        FIR_STOOL.register();
        GREEN_ENCHANTED_STOOL.register();
        HOLLY_STOOL.register();
        IMPARIUS_STOOL.register();
        JACARANDA_STOOL.register();
        LAMENT_STOOL.register();
        MAHOGANY_STOOL.register();
        MAPLE_STOOL.register();
        NIGHTSHADE_STOOL.register();
        PALM_STOOL.register();
        PINE_STOOL.register();
        RAINBOW_EUCALYPTUS_STOOL.register();
        REDWOOD_STOOL.register();
        SKYRIS_STOOL.register();
        SYTHIAN_STOOL.register();
        WILLOW_STOOL.register();
        WITCH_HAZEL_STOOL.register();
        ZELKOVA_STOOL.register();
    }
}
