package com.chimericdream.minekea.compat.byg;

import com.chimericdream.minekea.block.furniture.shelves.GenericFloatingShelf;
import com.chimericdream.minekea.block.furniture.shelves.GenericFloatingShelf.FloatingShelfSettings;
import com.chimericdream.minekea.block.furniture.shelves.GenericShelf;
import com.chimericdream.minekea.block.furniture.shelves.GenericShelf.SupportedShelfSettings;

public class BygShelves {
    public static final GenericShelf ASPEN_SHELF;
    public static final GenericShelf BAOBAB_SHELF;
    public static final GenericShelf BLUE_ENCHANTED_SHELF;
    public static final GenericShelf BULBIS_SHELF;
    public static final GenericShelf CHERRY_SHELF;
    public static final GenericShelf CIKA_SHELF;
    public static final GenericShelf CYPRESS_SHELF;
    public static final GenericShelf EBONY_SHELF;
    public static final GenericShelf EMBUR_SHELF;
    public static final GenericShelf ETHER_SHELF;
    public static final GenericShelf FIR_SHELF;
    public static final GenericShelf GREEN_ENCHANTED_SHELF;
    public static final GenericShelf HOLLY_SHELF;
    public static final GenericShelf IMPARIUS_SHELF;
    public static final GenericShelf JACARANDA_SHELF;
    public static final GenericShelf LAMENT_SHELF;
    public static final GenericShelf MAHOGANY_SHELF;
    public static final GenericShelf MAPLE_SHELF;
    public static final GenericShelf NIGHTSHADE_SHELF;
    public static final GenericShelf PALM_SHELF;
    public static final GenericShelf PINE_SHELF;
    public static final GenericShelf RAINBOW_EUCALYPTUS_SHELF;
    public static final GenericShelf REDWOOD_SHELF;
    public static final GenericShelf SKYRIS_SHELF;
    public static final GenericShelf SYTHIAN_SHELF;
    public static final GenericShelf WILLOW_SHELF;
    public static final GenericShelf WITCH_HAZEL_SHELF;
    public static final GenericShelf ZELKOVA_SHELF;

    public static final GenericFloatingShelf ASPEN_FLOATING_SHELF;
    public static final GenericFloatingShelf BAOBAB_FLOATING_SHELF;
    public static final GenericFloatingShelf BLUE_ENCHANTED_FLOATING_SHELF;
    public static final GenericFloatingShelf BULBIS_FLOATING_SHELF;
    public static final GenericFloatingShelf CHERRY_FLOATING_SHELF;
    public static final GenericFloatingShelf CIKA_FLOATING_SHELF;
    public static final GenericFloatingShelf CYPRESS_FLOATING_SHELF;
    public static final GenericFloatingShelf EBONY_FLOATING_SHELF;
    public static final GenericFloatingShelf EMBUR_FLOATING_SHELF;
    public static final GenericFloatingShelf ETHER_FLOATING_SHELF;
    public static final GenericFloatingShelf FIR_FLOATING_SHELF;
    public static final GenericFloatingShelf GREEN_ENCHANTED_FLOATING_SHELF;
    public static final GenericFloatingShelf HOLLY_FLOATING_SHELF;
    public static final GenericFloatingShelf IMPARIUS_FLOATING_SHELF;
    public static final GenericFloatingShelf JACARANDA_FLOATING_SHELF;
    public static final GenericFloatingShelf LAMENT_FLOATING_SHELF;
    public static final GenericFloatingShelf MAHOGANY_FLOATING_SHELF;
    public static final GenericFloatingShelf MAPLE_FLOATING_SHELF;
    public static final GenericFloatingShelf NIGHTSHADE_FLOATING_SHELF;
    public static final GenericFloatingShelf PALM_FLOATING_SHELF;
    public static final GenericFloatingShelf PINE_FLOATING_SHELF;
    public static final GenericFloatingShelf RAINBOW_EUCALYPTUS_FLOATING_SHELF;
    public static final GenericFloatingShelf REDWOOD_FLOATING_SHELF;
    public static final GenericFloatingShelf SKYRIS_FLOATING_SHELF;
    public static final GenericFloatingShelf SYTHIAN_FLOATING_SHELF;
    public static final GenericFloatingShelf WILLOW_FLOATING_SHELF;
    public static final GenericFloatingShelf WITCH_HAZEL_FLOATING_SHELF;
    public static final GenericFloatingShelf ZELKOVA_FLOATING_SHELF;

    static {
        ASPEN_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.ASPEN));
        BAOBAB_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.BAOBAB));
        BLUE_ENCHANTED_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.BLUE_ENCHANTED));
        BULBIS_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.BULBIS));
        CHERRY_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.CHERRY));
        CIKA_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.CIKA));
        CYPRESS_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.CYPRESS));
        EBONY_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.EBONY));
        EMBUR_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.EMBUR));
        ETHER_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.ETHER));
        FIR_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.FIR));
        GREEN_ENCHANTED_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.GREEN_ENCHANTED));
        HOLLY_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.HOLLY));
        IMPARIUS_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.IMPARIUS));
        JACARANDA_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.JACARANDA));
        LAMENT_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.LAMENT));
        MAHOGANY_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.MAHOGANY));
        MAPLE_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.MAPLE));
        NIGHTSHADE_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.NIGHTSHADE));
        PALM_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.PALM));
        PINE_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.PINE));
        RAINBOW_EUCALYPTUS_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.RAINBOW_EUCALYPTUS));
        REDWOOD_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.REDWOOD));
        SKYRIS_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.SKYRIS));
        SYTHIAN_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.SYTHIAN));
        WILLOW_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.WILLOW));
        WITCH_HAZEL_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.WITCH_HAZEL));
        ZELKOVA_SHELF = new GenericShelf(new SupportedShelfSettings(BygBlockSettings.ZELKOVA));

        ASPEN_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.ASPEN));
        BAOBAB_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.BAOBAB));
        BLUE_ENCHANTED_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.BLUE_ENCHANTED));
        BULBIS_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.BULBIS));
        CHERRY_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.CHERRY));
        CIKA_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.CIKA));
        CYPRESS_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.CYPRESS));
        EBONY_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.EBONY));
        EMBUR_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.EMBUR));
        ETHER_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.ETHER));
        FIR_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.FIR));
        GREEN_ENCHANTED_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.GREEN_ENCHANTED));
        HOLLY_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.HOLLY));
        IMPARIUS_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.IMPARIUS));
        JACARANDA_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.JACARANDA));
        LAMENT_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.LAMENT));
        MAHOGANY_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.MAHOGANY));
        MAPLE_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.MAPLE));
        NIGHTSHADE_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.NIGHTSHADE));
        PALM_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.PALM));
        PINE_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.PINE));
        RAINBOW_EUCALYPTUS_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.RAINBOW_EUCALYPTUS));
        REDWOOD_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.REDWOOD));
        SKYRIS_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.SKYRIS));
        SYTHIAN_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.SYTHIAN));
        WILLOW_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.WILLOW));
        WITCH_HAZEL_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.WITCH_HAZEL));
        ZELKOVA_FLOATING_SHELF = new GenericFloatingShelf(new FloatingShelfSettings(BygBlockSettings.ZELKOVA));
    }

    public void register() {
        ASPEN_SHELF.register();
        BAOBAB_SHELF.register();
        BLUE_ENCHANTED_SHELF.register();
        BULBIS_SHELF.register();
        CHERRY_SHELF.register();
        CIKA_SHELF.register();
        CYPRESS_SHELF.register();
        EBONY_SHELF.register();
        EMBUR_SHELF.register();
        ETHER_SHELF.register();
        FIR_SHELF.register();
        GREEN_ENCHANTED_SHELF.register();
        HOLLY_SHELF.register();
        IMPARIUS_SHELF.register();
        JACARANDA_SHELF.register();
        LAMENT_SHELF.register();
        MAHOGANY_SHELF.register();
        MAPLE_SHELF.register();
        NIGHTSHADE_SHELF.register();
        PALM_SHELF.register();
        PINE_SHELF.register();
        RAINBOW_EUCALYPTUS_SHELF.register();
        REDWOOD_SHELF.register();
        SKYRIS_SHELF.register();
        SYTHIAN_SHELF.register();
        WILLOW_SHELF.register();
        WITCH_HAZEL_SHELF.register();
        ZELKOVA_SHELF.register();

        ASPEN_FLOATING_SHELF.register();
        BAOBAB_FLOATING_SHELF.register();
        BLUE_ENCHANTED_FLOATING_SHELF.register();
        BULBIS_FLOATING_SHELF.register();
        CHERRY_FLOATING_SHELF.register();
        CIKA_FLOATING_SHELF.register();
        CYPRESS_FLOATING_SHELF.register();
        EBONY_FLOATING_SHELF.register();
        EMBUR_FLOATING_SHELF.register();
        ETHER_FLOATING_SHELF.register();
        FIR_FLOATING_SHELF.register();
        GREEN_ENCHANTED_FLOATING_SHELF.register();
        HOLLY_FLOATING_SHELF.register();
        IMPARIUS_FLOATING_SHELF.register();
        JACARANDA_FLOATING_SHELF.register();
        LAMENT_FLOATING_SHELF.register();
        MAHOGANY_FLOATING_SHELF.register();
        MAPLE_FLOATING_SHELF.register();
        NIGHTSHADE_FLOATING_SHELF.register();
        PALM_FLOATING_SHELF.register();
        PINE_FLOATING_SHELF.register();
        RAINBOW_EUCALYPTUS_FLOATING_SHELF.register();
        REDWOOD_FLOATING_SHELF.register();
        SKYRIS_FLOATING_SHELF.register();
        SYTHIAN_FLOATING_SHELF.register();
        WILLOW_FLOATING_SHELF.register();
        WITCH_HAZEL_FLOATING_SHELF.register();
        ZELKOVA_FLOATING_SHELF.register();
    }
}
