package com.chimericdream.minekea.block.building.beams;

import com.chimericdream.minekea.block.building.BuildingBlocks;
import com.chimericdream.minekea.block.building.general.BasaltBricksBlock;
import com.chimericdream.minekea.block.building.general.CrackedBasaltBricksBlock;
import com.chimericdream.minekea.block.building.general.CrimsonBasaltBricksBlock;
import com.chimericdream.minekea.block.building.general.MossyBasaltBricksBlock;
import com.chimericdream.minekea.block.building.general.WarpedBasaltBricksBlock;
import com.chimericdream.minekea.block.building.general.WarpedNetherBricksBlock;
import com.chimericdream.minekea.resource.TextureUtils;
import com.chimericdream.minekea.util.MinekeaBlock;
import com.chimericdream.minekea.util.MinekeaBlockCategory;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Blocks;

import java.util.ArrayList;
import java.util.List;

public class Beams implements MinekeaBlockCategory {
    public static final List<MinekeaBlock> BLOCKS = new ArrayList<>();

    static {
        BLOCKS.add(new GenericBeamBlock("amethyst", "Amethyst", Blocks.AMETHYST_BLOCK));
        BLOCKS.add(new GenericBeamBlock("andesite", "Andesite", Blocks.ANDESITE));
        BLOCKS.add(new GenericBeamBlock("basalt", "Basalt", Blocks.BASALT, TextureUtils.block(Blocks.BASALT, "_side"), TextureUtils.block(Blocks.BASALT, "_top")));
        BLOCKS.add(new GenericBeamBlock("basalt_brick", "Basalt Brick", BuildingBlocks.BASALT_BRICKS_BLOCK, TextureUtils.block(BasaltBricksBlock.BLOCK_ID)));
        BLOCKS.add(new GenericBeamBlock("blackstone", "Blackstone", Blocks.BLACKSTONE));
        BLOCKS.add(new GenericBeamBlock("bone", "Bone", Blocks.BONE_BLOCK, TextureUtils.block(Blocks.BONE_BLOCK, "_side"), TextureUtils.block(Blocks.BONE_BLOCK, "_top")));
        BLOCKS.add(new GenericBeamBlock("brick", "Brick", Blocks.BRICKS));
        BLOCKS.add(new GenericBeamBlock("calcite", "Calcite", Blocks.CALCITE));
        BLOCKS.add(new GenericBeamBlock("cobbled_deepslate", "Cobbled Deepslate", Blocks.COBBLED_DEEPSLATE));
        BLOCKS.add(new GenericBeamBlock("cobblestone", "Cobblestone", Blocks.COBBLESTONE));
        BLOCKS.add(new GenericBeamBlock("cracked_basalt_brick", "Cracked Basalt Brick", BuildingBlocks.CRACKED_BASALT_BRICKS_BLOCK, TextureUtils.block(CrackedBasaltBricksBlock.BLOCK_ID)));
        BLOCKS.add(new GenericBeamBlock("cracked_deepslate_brick", "Cracked Deepslate Brick", Blocks.CRACKED_DEEPSLATE_BRICKS));
        BLOCKS.add(new GenericBeamBlock("cracked_deepslate_tile", "Cracked Deepslate Tile", Blocks.CRACKED_DEEPSLATE_TILES));
        BLOCKS.add(new GenericBeamBlock("cracked_stone_brick", "Cracked Stone Brick", Blocks.CRACKED_STONE_BRICKS));
        BLOCKS.add(new GenericBeamBlock("crimson_basalt_brick", "Crimson Basalt Brick", BuildingBlocks.CRIMSON_BASALT_BRICKS_BLOCK, TextureUtils.block(CrimsonBasaltBricksBlock.BLOCK_ID)));
        BLOCKS.add(new GenericBeamBlock("crying_obsidian", "Crying Obsidian", Blocks.CRYING_OBSIDIAN));
        BLOCKS.add(new GenericBeamBlock("cut_red_sandstone", "Cut Red Sandstone", Blocks.CUT_RED_SANDSTONE));
        BLOCKS.add(new GenericBeamBlock("cut_sandstone", "Cut Sandstone", Blocks.CUT_SANDSTONE));
        BLOCKS.add(new GenericBeamBlock("dark_prismarine", "Dark Prismarine", Blocks.DARK_PRISMARINE));
        BLOCKS.add(new GenericBeamBlock("deepslate", "Deepslate", Blocks.DEEPSLATE));
        BLOCKS.add(new GenericBeamBlock("deepslate_brick", "Deepslate Brick", Blocks.DEEPSLATE_BRICKS));
        BLOCKS.add(new GenericBeamBlock("deepslate_tile", "Deepslate Tile", Blocks.DEEPSLATE_TILES));
        BLOCKS.add(new GenericBeamBlock("diorite", "Diorite", Blocks.DIORITE));
        BLOCKS.add(new GenericBeamBlock("end_stone", "End Stone", Blocks.END_STONE));
        BLOCKS.add(new GenericBeamBlock("end_stone_brick", "End Stone Brick", Blocks.END_STONE_BRICKS));
        BLOCKS.add(new GenericBeamBlock("granite", "Granite", Blocks.GRANITE));
        BLOCKS.add(new GenericBeamBlock("mossy_basalt_brick", "Mossy Basalt Brick", BuildingBlocks.MOSSY_BASALT_BRICKS_BLOCK, TextureUtils.block(MossyBasaltBricksBlock.BLOCK_ID)));
        BLOCKS.add(new GenericBeamBlock("mossy_cobblestone", "Mossy Cobblestone", Blocks.MOSSY_COBBLESTONE));
        BLOCKS.add(new GenericBeamBlock("mossy_stone_brick", "Mossy Stone Brick", Blocks.MOSSY_STONE_BRICKS));
        BLOCKS.add(new GenericBeamBlock("mud_brick", "Mud Brick", Blocks.MUD_BRICKS));
        BLOCKS.add(new GenericBeamBlock("netherrack", "Netherrack", Blocks.NETHERRACK));
        BLOCKS.add(new GenericBeamBlock("nether_brick", "Nether Brick", Blocks.NETHER_BRICKS));
        BLOCKS.add(new GenericBeamBlock("obsidian", "Obsidian", Blocks.OBSIDIAN));
        BLOCKS.add(new GenericBeamBlock("packed_mud", "Packed Mud", Blocks.PACKED_MUD));
        BLOCKS.add(new GenericBeamBlock("polished_andesite", "Polished Andesite", Blocks.POLISHED_ANDESITE));
        BLOCKS.add(new GenericBeamBlock("polished_basalt", "Polished Basalt", Blocks.POLISHED_BASALT, TextureUtils.block(Blocks.POLISHED_BASALT, "_side"), TextureUtils.block(Blocks.POLISHED_BASALT, "_top")));
        BLOCKS.add(new GenericBeamBlock("polished_blackstone", "Polished Blackstone", Blocks.POLISHED_BLACKSTONE));
        BLOCKS.add(new GenericBeamBlock("polished_blackstone_brick", "Polished Blackstone Brick", Blocks.POLISHED_BLACKSTONE_BRICKS));
        BLOCKS.add(new GenericBeamBlock("polished_deepslate", "Polished Deepslate", Blocks.POLISHED_DEEPSLATE));
        BLOCKS.add(new GenericBeamBlock("polished_diorite", "Polished Diorite", Blocks.POLISHED_DIORITE));
        BLOCKS.add(new GenericBeamBlock("polished_granite", "Polished Granite", Blocks.POLISHED_GRANITE));
        BLOCKS.add(new GenericBeamBlock("prismarine", "Prismarine", Blocks.PRISMARINE));
        BLOCKS.add(new GenericBeamBlock("prismarine_brick", "Prismarine Brick", Blocks.PRISMARINE_BRICKS));
        BLOCKS.add(new GenericBeamBlock("purpur", "Purpur", Blocks.PURPUR_BLOCK));
        BLOCKS.add(new GenericBeamBlock("purpur_pillar", "Purpur Pillar", Blocks.PURPUR_PILLAR));
        BLOCKS.add(new GenericBeamBlock("quartz", "Quartz", Blocks.QUARTZ_BLOCK, TextureUtils.block(Blocks.QUARTZ_BLOCK, "_top")));
        BLOCKS.add(new GenericBeamBlock("quartz_brick", "Quartz Brick", Blocks.QUARTZ_BRICKS));
        BLOCKS.add(new GenericBeamBlock("red_nether_brick", "Red Nether Brick", Blocks.RED_NETHER_BRICKS));
        BLOCKS.add(new GenericBeamBlock("red_sandstone", "Red Sandstone", Blocks.RED_SANDSTONE));
        BLOCKS.add(new GenericBeamBlock("sandstone", "Sandstone", Blocks.SANDSTONE));
        BLOCKS.add(new GenericBeamBlock("smooth_basalt", "Smooth Basalt", Blocks.SMOOTH_BASALT));
        BLOCKS.add(new GenericBeamBlock("smooth_quartz", "Smooth Quartz", Blocks.SMOOTH_QUARTZ, TextureUtils.block(Blocks.QUARTZ_BLOCK, "_bottom")));
        BLOCKS.add(new GenericBeamBlock("smooth_red_sandstone", "Smooth Red Sandstone", Blocks.SMOOTH_RED_SANDSTONE, TextureUtils.block(Blocks.RED_SANDSTONE, "_top")));
        BLOCKS.add(new GenericBeamBlock("smooth_sandstone", "Smooth Sandstone", Blocks.SMOOTH_SANDSTONE, TextureUtils.block(Blocks.SANDSTONE, "_top")));
        BLOCKS.add(new GenericBeamBlock("smooth_stone", "Smooth Stone", Blocks.SMOOTH_STONE));
        BLOCKS.add(new GenericBeamBlock("stone", "Stone", Blocks.STONE));
        BLOCKS.add(new GenericBeamBlock("stone_brick", "Stone Brick", Blocks.STONE_BRICKS));
        BLOCKS.add(new GenericBeamBlock("tuff", "Tuff", Blocks.TUFF));
        BLOCKS.add(new GenericBeamBlock("warped_basalt_brick", "Warped Basalt Brick", BuildingBlocks.WARPED_BASALT_BRICKS_BLOCK, TextureUtils.block(WarpedBasaltBricksBlock.BLOCK_ID)));
        BLOCKS.add(new GenericBeamBlock("warped_nether_brick", "Warped Nether Brick", BuildingBlocks.WARPED_NETHER_BRICKS_BLOCK, TextureUtils.block(WarpedNetherBricksBlock.BLOCK_ID)));
        BLOCKS.add(new GenericBeamBlock("copper_block", "Copper Block", Blocks.COPPER_BLOCK));
        BLOCKS.add(new GenericBeamBlock("diamond_block", "Diamond Block", Blocks.DIAMOND_BLOCK));
        BLOCKS.add(new GenericBeamBlock("gold_block", "Gold Block", Blocks.GOLD_BLOCK));
        BLOCKS.add(new GenericBeamBlock("iron_block", "Iron Block", Blocks.IRON_BLOCK));
        BLOCKS.add(new GenericBeamBlock("lapis_block", "Lapis Block", Blocks.LAPIS_BLOCK));
        BLOCKS.add(new GenericBeamBlock("netherite_block", "Netherite Block", Blocks.NETHERITE_BLOCK));
        BLOCKS.add(new GenericBeamBlock("redstone_block", "Redstone Block", Blocks.REDSTONE_BLOCK));
        BLOCKS.add(new GenericBeamBlock("cut_copper", "Cut Copper", Blocks.CUT_COPPER));
        BLOCKS.add(new GenericBeamBlock("exposed_cut_copper", "Exposed Cut Copper", Blocks.EXPOSED_CUT_COPPER));
        BLOCKS.add(new GenericBeamBlock("weathered_cut_copper", "Weathered Cut Copper", Blocks.WEATHERED_CUT_COPPER));
        BLOCKS.add(new GenericBeamBlock("oxidized_cut_copper", "Oxidized Cut Copper", Blocks.OXIDIZED_CUT_COPPER));
        BLOCKS.add(new GenericBeamBlock("white_terracotta", "White Terracotta", Blocks.WHITE_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("orange_terracotta", "Orange Terracotta", Blocks.ORANGE_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("magenta_terracotta", "Magenta Terracotta", Blocks.MAGENTA_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("light_blue_terracotta", "Light Blue Terracotta", Blocks.LIGHT_BLUE_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("yellow_terracotta", "Yellow Terracotta", Blocks.YELLOW_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("lime_terracotta", "Lime Terracotta", Blocks.LIME_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("pink_terracotta", "Pink Terracotta", Blocks.PINK_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("gray_terracotta", "Gray Terracotta", Blocks.GRAY_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("light_gray_terracotta", "Light Gray Terracotta", Blocks.LIGHT_GRAY_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("cyan_terracotta", "Cyan Terracotta", Blocks.CYAN_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("purple_terracotta", "Purple Terracotta", Blocks.PURPLE_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("blue_terracotta", "Blue Terracotta", Blocks.BLUE_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("brown_terracotta", "Brown Terracotta", Blocks.BROWN_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("green_terracotta", "Green Terracotta", Blocks.GREEN_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("red_terracotta", "Red Terracotta", Blocks.RED_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("black_terracotta", "Black Terracotta", Blocks.BLACK_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("white_glazed_terracotta", "White Glazed Terracotta", Blocks.WHITE_GLAZED_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("orange_glazed_terracotta", "Orange Glazed Terracotta", Blocks.ORANGE_GLAZED_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("magenta_glazed_terracotta", "Magenta Glazed Terracotta", Blocks.MAGENTA_GLAZED_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("light_blue_glazed_terracotta", "Light Blue Glazed Terracotta", Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("yellow_glazed_terracotta", "Yellow Glazed Terracotta", Blocks.YELLOW_GLAZED_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("lime_glazed_terracotta", "Lime Glazed Terracotta", Blocks.LIME_GLAZED_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("pink_glazed_terracotta", "Pink Glazed Terracotta", Blocks.PINK_GLAZED_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("gray_glazed_terracotta", "Gray Glazed Terracotta", Blocks.GRAY_GLAZED_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("light_gray_glazed_terracotta", "Light Gray Glazed Terracotta", Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("cyan_glazed_terracotta", "Cyan Glazed Terracotta", Blocks.CYAN_GLAZED_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("purple_glazed_terracotta", "Purple Glazed Terracotta", Blocks.PURPLE_GLAZED_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("blue_glazed_terracotta", "Blue Glazed Terracotta", Blocks.BLUE_GLAZED_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("brown_glazed_terracotta", "Brown Glazed Terracotta", Blocks.BROWN_GLAZED_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("green_glazed_terracotta", "Green Glazed Terracotta", Blocks.GREEN_GLAZED_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("red_glazed_terracotta", "Red Glazed Terracotta", Blocks.RED_GLAZED_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("black_glazed_terracotta", "Black Glazed Terracotta", Blocks.BLACK_GLAZED_TERRACOTTA));
        BLOCKS.add(new GenericBeamBlock("white_concrete", "White Concrete", Blocks.WHITE_CONCRETE));
        BLOCKS.add(new GenericBeamBlock("orange_concrete", "Orange Concrete", Blocks.ORANGE_CONCRETE));
        BLOCKS.add(new GenericBeamBlock("magenta_concrete", "Magenta Concrete", Blocks.MAGENTA_CONCRETE));
        BLOCKS.add(new GenericBeamBlock("light_blue_concrete", "Light Blue Concrete", Blocks.LIGHT_BLUE_CONCRETE));
        BLOCKS.add(new GenericBeamBlock("yellow_concrete", "Yellow Concrete", Blocks.YELLOW_CONCRETE));
        BLOCKS.add(new GenericBeamBlock("lime_concrete", "Lime Concrete", Blocks.LIME_CONCRETE));
        BLOCKS.add(new GenericBeamBlock("pink_concrete", "Pink Concrete", Blocks.PINK_CONCRETE));
        BLOCKS.add(new GenericBeamBlock("gray_concrete", "Gray Concrete", Blocks.GRAY_CONCRETE));
        BLOCKS.add(new GenericBeamBlock("light_gray_concrete", "Light Gray Concrete", Blocks.LIGHT_GRAY_CONCRETE));
        BLOCKS.add(new GenericBeamBlock("cyan_concrete", "Cyan Concrete", Blocks.CYAN_CONCRETE));
        BLOCKS.add(new GenericBeamBlock("purple_concrete", "Purple Concrete", Blocks.PURPLE_CONCRETE));
        BLOCKS.add(new GenericBeamBlock("blue_concrete", "Blue Concrete", Blocks.BLUE_CONCRETE));
        BLOCKS.add(new GenericBeamBlock("brown_concrete", "Brown Concrete", Blocks.BROWN_CONCRETE));
        BLOCKS.add(new GenericBeamBlock("green_concrete", "Green Concrete", Blocks.GREEN_CONCRETE));
        BLOCKS.add(new GenericBeamBlock("red_concrete", "Red Concrete", Blocks.RED_CONCRETE));
        BLOCKS.add(new GenericBeamBlock("black_concrete", "Black Concrete", Blocks.BLACK_CONCRETE));
        BLOCKS.add(new GenericBeamBlock("acacia", "Acacia", Blocks.ACACIA_PLANKS, true));
        BLOCKS.add(new GenericBeamBlock(AbstractBlock.Settings.copy(Blocks.ACACIA_PLANKS), "acacia_log", "Acacia Log", Blocks.ACACIA_LOG, true, TextureUtils.block(Blocks.ACACIA_LOG), TextureUtils.block(Blocks.ACACIA_LOG, "_top")));
        BLOCKS.add(new GenericBeamBlock("birch", "Birch", Blocks.BIRCH_PLANKS, true));
        BLOCKS.add(new GenericBeamBlock(AbstractBlock.Settings.copy(Blocks.BIRCH_PLANKS), "birch_log", "Birch Log", Blocks.BIRCH_LOG, true, TextureUtils.block(Blocks.BIRCH_LOG), TextureUtils.block(Blocks.BIRCH_LOG, "_top")));
        BLOCKS.add(new GenericBeamBlock("cherry", "Cherry", Blocks.CHERRY_PLANKS));
        BLOCKS.add(new GenericBeamBlock(AbstractBlock.Settings.copy(Blocks.CHERRY_PLANKS), "cherry_log", "Cherry Log", Blocks.CHERRY_LOG, true, TextureUtils.block(Blocks.CHERRY_LOG), TextureUtils.block(Blocks.CHERRY_LOG, "_top")));
        BLOCKS.add(new GenericBeamBlock("crimson", "Crimson", Blocks.CRIMSON_PLANKS));
        BLOCKS.add(new GenericBeamBlock(AbstractBlock.Settings.copy(Blocks.CRIMSON_PLANKS), "crimson_stem", "Crimson Stem", Blocks.CRIMSON_STEM, TextureUtils.block(Blocks.CRIMSON_STEM), TextureUtils.block(Blocks.CRIMSON_STEM, "_top")));
        BLOCKS.add(new GenericBeamBlock("dark_oak", "Dark Oak", Blocks.DARK_OAK_PLANKS, true));
        BLOCKS.add(new GenericBeamBlock(AbstractBlock.Settings.copy(Blocks.DARK_OAK_PLANKS), "dark_oak_log", "Dark Oak Log", Blocks.DARK_OAK_LOG, true, TextureUtils.block(Blocks.DARK_OAK_LOG), TextureUtils.block(Blocks.DARK_OAK_LOG, "_top")));
        BLOCKS.add(new GenericBeamBlock("jungle", "Jungle", Blocks.JUNGLE_PLANKS, true));
        BLOCKS.add(new GenericBeamBlock(AbstractBlock.Settings.copy(Blocks.JUNGLE_PLANKS), "jungle_log", "Jungle Log", Blocks.JUNGLE_LOG, true, TextureUtils.block(Blocks.JUNGLE_LOG), TextureUtils.block(Blocks.JUNGLE_LOG, "_top")));
        BLOCKS.add(new GenericBeamBlock("mangrove", "Mangrove", Blocks.MANGROVE_PLANKS, true));
        BLOCKS.add(new GenericBeamBlock(AbstractBlock.Settings.copy(Blocks.MANGROVE_PLANKS), "mangrove_log", "Mangrove Log", Blocks.MANGROVE_LOG, true, TextureUtils.block(Blocks.MANGROVE_LOG), TextureUtils.block(Blocks.MANGROVE_LOG, "_top")));
        BLOCKS.add(new GenericBeamBlock("oak", "Oak", Blocks.OAK_PLANKS, true));
        BLOCKS.add(new GenericBeamBlock(AbstractBlock.Settings.copy(Blocks.OAK_PLANKS), "oak_log", "Oak Log", Blocks.OAK_LOG, true, TextureUtils.block(Blocks.OAK_LOG), TextureUtils.block(Blocks.OAK_LOG, "_top")));
        BLOCKS.add(new GenericBeamBlock("spruce", "Spruce", Blocks.SPRUCE_PLANKS, true));
        BLOCKS.add(new GenericBeamBlock(AbstractBlock.Settings.copy(Blocks.SPRUCE_PLANKS), "spruce_log", "Spruce Log", Blocks.SPRUCE_LOG, true, TextureUtils.block(Blocks.SPRUCE_LOG), TextureUtils.block(Blocks.SPRUCE_LOG, "_top")));
        BLOCKS.add(new GenericBeamBlock("warped", "Warped", Blocks.WARPED_PLANKS));
        BLOCKS.add(new GenericBeamBlock(AbstractBlock.Settings.copy(Blocks.WARPED_PLANKS), "warped_stem", "Warped Stem", Blocks.WARPED_STEM, TextureUtils.block(Blocks.WARPED_STEM), TextureUtils.block(Blocks.WARPED_STEM, "_top")));
    }

    @Override
    public List<MinekeaBlock> getCategoryBlocks() {
        return BLOCKS;
    }
}
